export const UI_STRINGS = {
  es: {
    theArtist: 'El Artista',
    scrollExplore: 'Haz scroll para explorar',
    sectionAboutLabel: 'Sobre mí',
    sectionCraftLabel: 'El Arte',
    sectionPortfolioLabel: 'Portfolio',
    sectionBookLabel: 'Reservar Sesión',
    loading: 'Cargando el arte...',
    adminLink: 'Admin',
    contactEmail: 'Correo',
    contactInstagram: 'Instagram',
    contactLocation: 'Ubicación',
    bookButton: 'Contáctame',
    portfolioInstagramButton: 'Ver otros trabajos en Instagram',
    portfolioOpenImage: 'Abrir imagen en tamaño completo',
    portfolioViewerDialog: 'Visor de imágenes del portfolio',
    portfolioCloseViewer: 'Cerrar visor',
    portfolioZoomIn: 'Acercar imagen',
    portfolioZoomOut: 'Alejar imagen',
    portfolioZoomReset: 'Restablecer zoom',
    portfolioPrevImage: 'Ver diseño anterior',
    portfolioNextImage: 'Ver diseño siguiente',
  },
  en: {
    theArtist: 'The Artist',
    scrollExplore: 'Scroll to explore',
    sectionAboutLabel: 'About',
    sectionCraftLabel: 'The Craft',
    sectionPortfolioLabel: 'Portfolio',
    sectionBookLabel: 'Book a Session',
    loading: 'Loading the art...',
    adminLink: 'Admin',
    contactEmail: 'Email',
    contactInstagram: 'Instagram',
    contactLocation: 'Location',
    bookButton: 'Get in Touch',
    portfolioInstagramButton: 'See more work on Instagram',
    portfolioOpenImage: 'Open image in full size',
    portfolioViewerDialog: 'Portfolio image viewer',
    portfolioCloseViewer: 'Close viewer',
    portfolioZoomIn: 'Zoom in',
    portfolioZoomOut: 'Zoom out',
    portfolioZoomReset: 'Reset zoom',
    portfolioPrevImage: 'View previous design',
    portfolioNextImage: 'View next design',
  },
} as const;

export type UIStrings = (typeof UI_STRINGS)['es'];
